/**
 * Exposes the inline mockEngine catalogs as inspectable "datasets"
 * for Data Explorer — these are NOT external Parquet/CSV files.
 */

import {
  CITIES,
  getCityRadar,
  predictSkillRisk,
  SKILLS,
  TARGET_ROLES,
} from "@/services/mockEngine";

export type CatalogRow = Record<string, string | number>;

export interface CatalogDataset {
  id: string;
  name: string;
  description: string;
  source: string;
  kind: "Demo Data";
  columns: { name: string; type: "string" | "number" }[];
  rows: CatalogRow[];
}

function skillRiskRows(): CatalogRow[] {
  const city = "Bengaluru";
  return SKILLS.map((skill) => {
    const p = predictSkillRisk(skill, city, 3);
    return {
      skill: p.skill,
      city: p.city,
      experienceYears: p.experienceYears,
      exposureScore: p.exposureScore,
      exposureBand: p.exposureBand,
      halfLifeMonths: p.halfLifeMonths,
      tier1DecayVelocity: p.tier1DecayVelocity,
      tier2GrowthRate: p.tier2GrowthRate,
    };
  });
}

function cityRows(): CatalogRow[] {
  return CITIES.map((city) => {
    const r = getCityRadar(city);
    return {
      city: r.city,
      tier: r.tier,
      activeTechIndex: r.activeTechIndex,
      gccGrowthRate: r.gccGrowthRate,
      topSurge: r.surgingSkills[0]?.skill ?? "",
      topDecay: r.decayingSkills[0]?.skill ?? "",
    };
  });
}

function geoRows(): CatalogRow[] {
  const radar = getCityRadar("Bengaluru");
  return radar.geoClusters.map((g) => ({
    city: g.city,
    lat: g.lat,
    lon: g.lon,
    demand: g.demand,
    tier: g.tier,
  }));
}

export function getCatalogDatasets(): CatalogDataset[] {
  const riskRows = skillRiskRows();
  const cities = cityRows();
  const geo = geoRows();

  return [
    {
      id: "skill-risk-catalog",
      name: "Skill Risk Catalog (simulated)",
      description:
        "One mock prediction per catalog skill at Bengaluru / 3 years experience. Generated by predictSkillRisk.",
      source: "src/services/mockEngine.ts → predictSkillRisk + SKILLS",
      kind: "Demo Data",
      columns: [
        { name: "skill", type: "string" },
        { name: "city", type: "string" },
        { name: "experienceYears", type: "number" },
        { name: "exposureScore", type: "number" },
        { name: "exposureBand", type: "string" },
        { name: "halfLifeMonths", type: "number" },
        { name: "tier1DecayVelocity", type: "number" },
        { name: "tier2GrowthRate", type: "number" },
      ],
      rows: riskRows,
    },
    {
      id: "city-profiles",
      name: "City Profiles (simulated)",
      description: "ATI and GCC growth from getCityRadar for each hardcoded hub.",
      source: "src/services/mockEngine.ts → getCityRadar + CITY_PROFILES",
      kind: "Demo Data",
      columns: [
        { name: "city", type: "string" },
        { name: "tier", type: "string" },
        { name: "activeTechIndex", type: "number" },
        { name: "gccGrowthRate", type: "number" },
        { name: "topSurge", type: "string" },
        { name: "topDecay", type: "string" },
      ],
      rows: cities,
    },
    {
      id: "geo-demand",
      name: "Geo Demand Clusters (simulated)",
      description: "Lat/lon markers and seeded demand used by the India SVG map.",
      source: "geoClusters from getCityRadar",
      kind: "Demo Data",
      columns: [
        { name: "city", type: "string" },
        { name: "lat", type: "number" },
        { name: "lon", type: "number" },
        { name: "demand", type: "number" },
        { name: "tier", type: "string" },
      ],
      rows: geo,
    },
    {
      id: "skill-list",
      name: "Skill Catalog",
      description: "Static autocomplete list — not a training corpus.",
      source: "SKILLS constant",
      kind: "Demo Data",
      columns: [{ name: "skill", type: "string" }],
      rows: SKILLS.map((skill) => ({ skill })),
    },
    {
      id: "target-roles",
      name: "Target Roles Catalog",
      description: "Static roles for Transition Planner.",
      source: "TARGET_ROLES constant",
      kind: "Demo Data",
      columns: [{ name: "role", type: "string" }],
      rows: TARGET_ROLES.map((role) => ({ role })),
    },
  ];
}

export function datasetToCsv(ds: CatalogDataset): string {
  const headers = ds.columns.map((c) => c.name);
  const lines = [
    headers.join(","),
    ...ds.rows.map((row) =>
      headers
        .map((h) => {
          const v = row[h];
          const s = v == null ? "" : String(v);
          return s.includes(",") || s.includes('"') ? `"${s.replace(/"/g, '""')}"` : s;
        })
        .join(","),
    ),
  ];
  return lines.join("\n");
}

export function summarizeColumns(rows: CatalogRow[], columns: string[]) {
  return columns.map((col) => {
    const vals = rows.map((r) => r[col]);
    const missing = vals.filter((v) => v === "" || v == null).length;
    const nums = vals.filter((v): v is number => typeof v === "number");
    const isNum = nums.length > vals.length * 0.6;
    if (isNum && nums.length) {
      const min = Math.min(...nums);
      const max = Math.max(...nums);
      const mean = nums.reduce((a, b) => a + b, 0) / nums.length;
      return { col, type: "number" as const, missing, min, max, mean: Math.round(mean * 100) / 100 };
    }
    const unique = new Set(vals.map(String)).size;
    return { col, type: "string" as const, missing, unique, min: null, max: null, mean: null };
  });
}
